// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.0
// - protoc             v5.26.1
// source: greeter/greeter.proto

package greeter

import (
	"context"

	"github.com/mangohow/mangokit/serialize"
	"github.com/mangohow/mangokit/tools"
	http "github.com/mangohow/mangokit/transport/http"
)

// GreeterHTTPService Examples:
type GreeterHTTPService interface {
	// SayHello Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterHTTPService(server *http.Server, svc GreeterHTTPService) {
	server.RegisterService(_GreeterHTTPService_serviceDesc, svc)
}

func _Greeter_SayHello_HTTP_Handler(svc interface{}, middleware http.Middleware) http.Middleware {
	return func(ctx context.Context, req interface{}, next http.NextHandler) error {
		in := new(HelloRequest)
		err := http.BindVar(ctx, in)
		if err != nil {
			return err
		}

		handler := func(ctx context.Context, req interface{}) error {
			ctxt := tools.GinCtxFromContext(ctx)
			reply, err := svc.(GreeterHTTPService).SayHello(ctx, in)
			if err != nil {
				return err
			}
			ctxt.JSON(http.StatusOK, serialize.Response{Data: reply})

			return nil
		}

		if middleware == nil {
			return handler(ctx, in)
		}

		return middleware(ctx, in, handler)
	}
}

var _GreeterHTTPService_serviceDesc = &http.ServiceDesc{
	HandlerType: (*GreeterHTTPService)(nil),
	Methods: []http.MethodDesc{
		{
			Method:  "GET",
			Path:    "/greeter",
			Handler: _Greeter_SayHello_HTTP_Handler,
		},
	},
}
