// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1-devel
// 	protoc        v3.20.1
// source: api/errors/v1/proto/errors.proto

package v1

import (
	_ "github.com/mangohow/mangokit/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 为某个枚举单独设置错误码
	ErrorReason_UserNotFound   ErrorReason = 0
	ErrorReason_ContentMissing ErrorReason = 1
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "UserNotFound",
		1: "ContentMissing",
	}
	ErrorReason_value = map[string]int32{
		"UserNotFound":   0,
		"ContentMissing": 1,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_errors_v1_proto_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_api_errors_v1_proto_errors_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_errors_v1_proto_errors_proto_rawDescGZIP(), []int{0}
}

var File_api_errors_v1_proto_errors_proto protoreflect.FileDescriptor

var file_api_errors_v1_proto_errors_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x13, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2a, 0x69, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x12, 0x28, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e,
	0x64, 0x10, 0x00, 0x1a, 0x16, 0xa8, 0x45, 0x94, 0x03, 0xb2, 0x45, 0x0f, 0xe7, 0x94, 0xa8, 0xe6,
	0x88, 0xb7, 0xe4, 0xb8, 0x8d, 0xe5, 0xad, 0x98, 0xe5, 0x9c, 0xa8, 0x12, 0x2a, 0x0a, 0x0e, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x1a,
	0x16, 0xa8, 0x45, 0x90, 0x03, 0xb2, 0x45, 0x0f, 0xe5, 0x86, 0x85, 0xe5, 0xae, 0xb9, 0xe4, 0xb8,
	0x8d, 0xe5, 0xad, 0x98, 0xe5, 0x9c, 0xa8, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x12, 0x5a,
	0x10, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_errors_v1_proto_errors_proto_rawDescOnce sync.Once
	file_api_errors_v1_proto_errors_proto_rawDescData = file_api_errors_v1_proto_errors_proto_rawDesc
)

func file_api_errors_v1_proto_errors_proto_rawDescGZIP() []byte {
	file_api_errors_v1_proto_errors_proto_rawDescOnce.Do(func() {
		file_api_errors_v1_proto_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_errors_v1_proto_errors_proto_rawDescData)
	})
	return file_api_errors_v1_proto_errors_proto_rawDescData
}

var file_api_errors_v1_proto_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_errors_v1_proto_errors_proto_goTypes = []interface{}{
	(ErrorReason)(0), // 0: errors.v1.ErrorReason
}
var file_api_errors_v1_proto_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_errors_v1_proto_errors_proto_init() }
func file_api_errors_v1_proto_errors_proto_init() {
	if File_api_errors_v1_proto_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_errors_v1_proto_errors_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_errors_v1_proto_errors_proto_goTypes,
		DependencyIndexes: file_api_errors_v1_proto_errors_proto_depIdxs,
		EnumInfos:         file_api_errors_v1_proto_errors_proto_enumTypes,
	}.Build()
	File_api_errors_v1_proto_errors_proto = out.File
	file_api_errors_v1_proto_errors_proto_rawDesc = nil
	file_api_errors_v1_proto_errors_proto_goTypes = nil
	file_api_errors_v1_proto_errors_proto_depIdxs = nil
}
