// Code generated by protoc-gen-go-error. DO NOT EDIT.
// versions:
// - protoc-gen-go-error v1.0.0
// - protoc              v3.20.1
// source: api/errors/v1/proto/errors.proto

package v1

import (
	"fmt"

	"github.com/mangohow/mangokit/errors"
)

const (
	Desc_UserNotFound   = "用户不存在"
	Desc_ContentMissing = "内容不存在"
)

var (
	ErrorUserNotFound   = errors.New(int32(ErrorReason_UserNotFound), 404, "UserNotFound", Desc_UserNotFound)
	ErrorContentMissing = errors.New(int32(ErrorReason_ContentMissing), 400, "ContentMissing", Desc_ContentMissing)
)

// 为某个枚举单独设置错误码
func NewErrorUserNotFound(format string, args ...interface{}) errors.Error {
	return errors.New(int32(ErrorReason_UserNotFound), 404, ErrorReason_UserNotFound.String(), fmt.Sprintf(format, args...))
}

func NewErrorContentMissing(format string, args ...interface{}) errors.Error {
	return errors.New(int32(ErrorReason_ContentMissing), 400, ErrorReason_ContentMissing.String(), fmt.Sprintf(format, args...))
}
