// Code generated by protoc-gen-go-error. DO NOT EDIT.
// versions:
// - protoc-gen-go-error v1.0.0
// - protoc              v3.20.1
// source: errors/v1/proto/errors.proto

package v1

import (
	"fmt"

	"github.com/mangohow/mangokit/errors"
)

// 为某个枚举单独设置错误码
func ErrorUserNotFound(format string, args ...interface{}) errors.Error {
	return errors.New(int32(ErrorReason_USER_NOT_FOUND), 404, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func ErrorContentMissing(format string, args ...interface{}) errors.Error {
	return errors.New(int32(ErrorReason_CONTENT_MISSING), 400, ErrorReason_CONTENT_MISSING.String(), fmt.Sprintf(format, args...))
}
