// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1-devel
// 	protoc        v5.26.1
// source: api/errors/errors.proto

package errors

import (
	_ "github.com/mangohow/mangokit/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 设置错误码
type ErrorReason int32

const (
	ErrorReason_Placeholder        ErrorReason = 0
	ErrorReason_NameCantNotBeEmpty ErrorReason = 1
	ErrorReason_XXX                ErrorReason = 2
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "Placeholder",
		1: "NameCantNotBeEmpty",
		2: "XXX",
	}
	ErrorReason_value = map[string]int32{
		"Placeholder":        0,
		"NameCantNotBeEmpty": 1,
		"XXX":                2,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_errors_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_api_errors_errors_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_errors_errors_proto_rawDescGZIP(), []int{0}
}

var File_api_errors_errors_proto protoreflect.FileDescriptor

var file_api_errors_errors_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x6c, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f,
	0x6c, 0x64, 0x65, 0x72, 0x10, 0x00, 0x12, 0x31, 0x0a, 0x12, 0x4e, 0x61, 0x6d, 0x65, 0x43, 0x61,
	0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x42, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x10, 0x01, 0x1a, 0x19,
	0xa8, 0x45, 0x90, 0x03, 0xb2, 0x45, 0x12, 0xe5, 0xa7, 0x93, 0xe5, 0x90, 0x8d, 0xe4, 0xb8, 0x8d,
	0xe8, 0x83, 0xbd, 0xe4, 0xb8, 0xba, 0xe7, 0xa9, 0xba, 0x12, 0x13, 0x0a, 0x03, 0x58, 0x58, 0x58,
	0x10, 0x02, 0x1a, 0x0a, 0xa8, 0x45, 0x90, 0x03, 0xb2, 0x45, 0x03, 0x78, 0x78, 0x78, 0x1a, 0x04,
	0xa0, 0x45, 0xf4, 0x03, 0x42, 0x13, 0x5a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x3b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_errors_errors_proto_rawDescOnce sync.Once
	file_api_errors_errors_proto_rawDescData = file_api_errors_errors_proto_rawDesc
)

func file_api_errors_errors_proto_rawDescGZIP() []byte {
	file_api_errors_errors_proto_rawDescOnce.Do(func() {
		file_api_errors_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_errors_errors_proto_rawDescData)
	})
	return file_api_errors_errors_proto_rawDescData
}

var file_api_errors_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_errors_errors_proto_goTypes = []interface{}{
	(ErrorReason)(0), // 0: errors.ErrorReason
}
var file_api_errors_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_errors_errors_proto_init() }
func file_api_errors_errors_proto_init() {
	if File_api_errors_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_errors_errors_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_errors_errors_proto_goTypes,
		DependencyIndexes: file_api_errors_errors_proto_depIdxs,
		EnumInfos:         file_api_errors_errors_proto_enumTypes,
	}.Build()
	File_api_errors_errors_proto = out.File
	file_api_errors_errors_proto_rawDesc = nil
	file_api_errors_errors_proto_goTypes = nil
	file_api_errors_errors_proto_depIdxs = nil
}
