// Code generated by protoc-gen-go-error. DO NOT EDIT.
// versions:
// - protoc-gen-go-error v1.0.0
// - protoc              v5.26.1
// source: api/errors/errors.proto

package errors

import (
	"fmt"

	"github.com/mangohow/mangokit/errors"
)

const (
	Desc_NameCantNotBeEmpty = "姓名不能为空"
	Desc_XXX                = "xxx"
)

var (
	ErrorNameCantNotBeEmpty = errors.New(int32(ErrorReason_NameCantNotBeEmpty), 400, "NameCantNotBeEmpty", Desc_NameCantNotBeEmpty)
	ErrorXXX                = errors.New(int32(ErrorReason_XXX), 400, "XXX", Desc_XXX)
)

func NewErrorPlaceholder(format string, args ...interface{}) errors.Error {
	return errors.New(int32(ErrorReason_Placeholder), 500, ErrorReason_Placeholder.String(), fmt.Sprintf(format, args...))
}

func NewErrorNameCantNotBeEmpty(format string, args ...interface{}) errors.Error {
	return errors.New(int32(ErrorReason_NameCantNotBeEmpty), 400, ErrorReason_NameCantNotBeEmpty.String(), fmt.Sprintf(format, args...))
}

func NewErrorXxx(format string, args ...interface{}) errors.Error {
	return errors.New(int32(ErrorReason_XXX), 400, ErrorReason_XXX.String(), fmt.Sprintf(format, args...))
}
