server:
  http:
    addr: ":8080"
    name: "unknown"
    version: "v1.0.0"

data:
  mysql:
    dataSourceName: "root:root@(127.0.0.1:3306)/blog?charset=utf8mb4&parseTime=true&loc=Local"
    maxOpenConns: 20
    maxIdleConns: 10

logger:
  level: "DEBUG"
  filePath: "log_file"
  fileName: "server.log"
  output: 0
  formatter: 0
  caller: true