// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.0
// - protoc             v5.26.1
// source: helloworld/greeter.proto

package helloworld

import (
	"context"
	"net/http"

	"github.com/mangohow/mangokit/serialize"
	"github.com/mangohow/mangokit/tools"
	"github.com/mangohow/mangokit/transport/httpwrapper"
)

// GreeterHTTPService Examples:
type GreeterHTTPService interface {
	// SayHello Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	GetError(context.Context, *GetErrorRequest) error
	AddUser(context.Context, *AddUserRequest) error
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
}

func RegisterGreeterHTTPService(server *httpwrapper.Server, svc GreeterHTTPService) {
	server.RegisterService(_GreeterHTTPService_serviceDesc, svc)
}

func _Greeter_SayHello_HTTP_Handler(svc interface{}, middleware httpwrapper.Middleware) httpwrapper.Middleware {
	return func(ctx context.Context, req interface{}, next httpwrapper.NextHandler) error {
		in := new(HelloRequest)
		err := tools.BindVar(ctx, in)
		if err != nil {
			return err
		}
		handler := func(ctx context.Context, req interface{}) error {
			ctxt := tools.GinCtxFromContext(ctx)
			reply, err := svc.(GreeterHTTPService).SayHello(ctx, in)

			if err != nil {
				return err
			}
			ctxt.JSON(http.StatusOK, serialize.Response{Data: reply})

			return nil
		}

		if middleware == nil {
			return handler(ctx, in)
		}

		return middleware(ctx, in, handler)
	}
}

func _Greeter_GetError_HTTP_Handler(svc interface{}, middleware httpwrapper.Middleware) httpwrapper.Middleware {
	return func(ctx context.Context, req interface{}, next httpwrapper.NextHandler) error {
		in := new(GetErrorRequest)
		err := tools.BindVar(ctx, in)
		if err != nil {
			return err
		}
		handler := func(ctx context.Context, req interface{}) error {
			ctxt := tools.GinCtxFromContext(ctx)
			err := svc.(GreeterHTTPService).GetError(ctx, in)

			if err != nil {
				return err
			}
			ctxt.Status(http.StatusOK)

			return nil
		}

		if middleware == nil {
			return handler(ctx, in)
		}

		return middleware(ctx, in, handler)
	}
}

func _Greeter_AddUser_HTTP_Handler(svc interface{}, middleware httpwrapper.Middleware) httpwrapper.Middleware {
	return func(ctx context.Context, req interface{}, next httpwrapper.NextHandler) error {
		in := new(AddUserRequest)
		err := tools.BindVar(ctx, in)
		if err != nil {
			return err
		}
		handler := func(ctx context.Context, req interface{}) error {
			ctxt := tools.GinCtxFromContext(ctx)
			err := svc.(GreeterHTTPService).AddUser(ctx, in)

			if err != nil {
				return err
			}
			ctxt.Status(http.StatusOK)

			return nil
		}

		if middleware == nil {
			return handler(ctx, in)
		}

		return middleware(ctx, in, handler)
	}
}

func _Greeter_GetUserInfo_HTTP_Handler(svc interface{}, middleware httpwrapper.Middleware) httpwrapper.Middleware {
	return func(ctx context.Context, req interface{}, next httpwrapper.NextHandler) error {
		in := new(GetUserInfoRequest)
		err := tools.BindVar(ctx, in)
		if err != nil {
			return err
		}
		handler := func(ctx context.Context, req interface{}) error {
			ctxt := tools.GinCtxFromContext(ctx)
			reply, err := svc.(GreeterHTTPService).GetUserInfo(ctx, in)

			if err != nil {
				return err
			}
			ctxt.JSON(http.StatusOK, serialize.Response{Data: reply})

			return nil
		}

		if middleware == nil {
			return handler(ctx, in)
		}

		return middleware(ctx, in, handler)
	}
}

var _GreeterHTTPService_serviceDesc = &httpwrapper.ServiceDesc{
	HandlerType: (*GreeterHTTPService)(nil),
	Methods: []httpwrapper.MethodDesc{
		{
			Method:  "GET",
			Path:    "/helloworld/:name",
			Handler: _Greeter_SayHello_HTTP_Handler,
		},
		{
			Method:  "GET",
			Path:    "/helloworld/:name",
			Handler: _Greeter_GetError_HTTP_Handler,
		},
		{
			Method:  "GET",
			Path:    "/helloworld/:name",
			Handler: _Greeter_AddUser_HTTP_Handler,
		},
		{
			Method:  "GET",
			Path:    "/helloworld/:name",
			Handler: _Greeter_GetUserInfo_HTTP_Handler,
		},
	},
}
